### ISSUE TITLE
PK has wrong format

### ISSUE THREAD

**Issue by randb1t** [DeFireX/autoCompounder#1]
DFX price 2.459577888953036
BNB price 401.71306195
Script running in only *with profit* mode
Error: PK has wrong format
    at /home/bnb/autoCompounder/index.js:57:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

PK has wrong format?   

is need 64 hex?
how to convert?

**Comment by randb1t** [comment]
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker
/usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@5.1.1
added 179 packages from 199 contributors in 26.313s

**Comment by KENoETH** [comment]
> DFX price 2.459577888953036 BNB price 401.71306195 Script running in only _with profit_ mode Error: PK has wrong format at /home/bnb/autoCompounder/index.js:57:19 at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> PK has wrong format?
> 
> is need 64 hex? how to convert?

**Comment by Smyak** [comment]
Correct PK format is 64 symbol HEX string without 0x prefix, for example d9bbac7576a5e6196336008aba4efafa436b0cbfcc59d00c9dab37b0e38d48f7
